import profile from "../../src/media/img/profile-picture.jpg";
import { MyUser, users } from "./objUsers";

const myUser = MyUser;
const User1 = users.find((user) => user.PhoneNumber === "0540001001");
const User2 = users.find((user) => user.PhoneNumber === "0540001002");
const User3 = users.find((user) => user.PhoneNumber === "0540001003");
const User4 = users.find((user) => user.PhoneNumber === "0540001004");

export const GroupJSON = {
  "97d5f888-9bec-4524-a743-46b02f54fc95": {
    GroupName: "Group1",
    ImgGroup: profile,
    DateTime: new Date(`Mon Jul 03 2023 08:16:00`),
    Description: "description of the group",
    PrincipalAdminId: User1.PhoneNumber,
    PrincipalAdminName: User1.FullName,
    Friends: [
      {
        PhoneNumber: User1.PhoneNumber,
        FirstName: User1.FirstName,
        LastName: User1.LastName,
        Img: User1.Img,
        IfManager: true,
        Status: "Principal Admin",
        IfLeft: false,
        DepartureDate: [
          {
            DateOut: null,
          },
        ],
        JoiningDate: [
          {
            DateIn: new Date(`Mon Jul 03 2023 08:16:00`),
          },
        ],
      },
      {
        PhoneNumber: myUser.Id,
        FirstName: myUser.Name,
        LastName: myUser.Last,
        Img: myUser.Img,
        IfManager: true,
        Status: "Administrator",
        IfLeft: false,
        DepartureDate: [
          {
            DateOut: new Date(`Tue Jul 04 2023 03:22:00`),
          },
          {
            DateOut: null,
          },
        ],
        JoiningDate: [
          {
            DateIn: new Date(`Mon Jul 03 2023 08:16:00`),
          },
          {
            DateIn: new Date(`Wed Jul 05 2023 04:18:00`),
          },
        ],
      },
      {
        PhoneNumber: User2.PhoneNumber,
        FirstName: User2.FirstName,
        LastName: User2.LastName,
        Img: User2.Img,
        IfManager: true,
        Status: "Administrator",
        IfLeft: false,
        DepartureDate: [
          {
            DateOut: null,
          },
        ],
        JoiningDate: [
          {
            DateIn: new Date(`Mon Jul 03 2023 08:16:00`),
          },
        ],
      },
      {
        PhoneNumber: User3.PhoneNumber,
        FirstName: User3.FirstName,
        LastName: User3.LastName,
        Img: User3.Img,
        IfManager: false,
        Status: "",
        IfLeft: false,
        DepartureDate: [
          {
            DateOut: null,
          },
        ],
        JoiningDate: [
          {
            DateIn: new Date(`Mon Jul 03 2023 08:16:00`),
          },
        ],
      },
      {
        PhoneNumber: User4.PhoneNumber,
        FirstName: User4.FirstName,
        LastName: User4.LastName,
        Img: User4.Img,
        IfManager: false,
        Status: "",
        IfLeft: false,
        DepartureDate: [
          {
            DateOut: null,
          },
        ],
        JoiningDate: [
          {
            DateIn: new Date(`Mon Jul 03 2023 08:16:00`),
          },
        ],
      },
    ],
    messages: [
      {
        MessagesId: "150dcaab-30a5-46c3-bb2f-cb1cffb25f81",
        IdOfUser: "",
        FromUser: "",
        Image: "",
        DateTimeOfMsg: new Date(`Mon Jul 03 2023 08:16:00`),
        message: `${User1.FullName} created the group`,
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: true,
      },
      {
        MessagesId: "3aecc370-6134-4673-85e3-3e73bd518ff0",
        IdOfUser: "",
        FromUser: "",
        Image: "",
        DateTimeOfMsg: new Date(`Mon Jul 03 2023 08:16:00`),
        message: `${User1.FullName} added ${myUser.FullName}, ${User2.FullName}, ${User3.FullName}, ${User4.FullName}`,
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: true,
      },
      {
        MessagesId: "873427cc-b0f0-4137-8a1e-8fe3982cc69e",
        IdOfUser: myUser.Id,
        FromUser: myUser.Name,
        Image: myUser.Img,
        DateTimeOfMsg: new Date(`Mon Jul 03 2023 09:00:00`),
        message: "aaaa",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 1,
        IdOfUser: User4.PhoneNumber,
        FromUser: User4.FullName,
        Image: User4.Img,
        DateTimeOfMsg: new Date(`Mon Jul 03 2023 10:00:00`),
        message: "Hello!",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: "44c6c7ca-ac31-43dc-841d-be8a7a900037",
        IdOfUser: "",
        FromUser: "",
        Image: "",
        DateTimeOfMsg: new Date(`Tue Jul 04 2023 03:22:00`),
        message: `${myUser.FullName} has left the group`,
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: true,
      },
      {
        MessagesId: 2,
        IdOfUser: User2.PhoneNumber,
        FromUser: User2.FullName,
        Image: User2.Img,
        DateTimeOfMsg: new Date(`Tue Jul 04 2023 11:30:00`),
        message: "Hello1",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 3,
        IdOfUser: User2.PhoneNumber,
        FromUser: User2.FullName,
        Image: User2.Img,
        DateTimeOfMsg: new Date(`Tue Jul 04 2023 11:31:00`),
        message: "aaaa",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 4,
        IdOfUser: User1.PhoneNumber,
        FromUser: User1.FullName,
        Image: User1.Img,
        DateTimeOfMsg: new Date(`Tue Jul 04 2023 11:32:00`),
        message: "Hello3",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: "ca5b328c-14f1-4d96-8fb2-215edbdccd3e",
        IdOfUser: "",
        FromUser: "",
        Image: "",
        DateTimeOfMsg: new Date(`Wed Jul 05 2023 04:18:00`),
        message: `${User1.FullName} added ${myUser.FullName}`,
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: true,
      },
      {
        MessagesId: "effb590a-5a38-4fe0-803f-04842ae9dca2",
        IdOfUser: "",
        FromUser: "",
        Image: "",
        DateTimeOfMsg: new Date(`Wed Jul 05 2023 04:18:00`),
        message: `${User1.FullName} set ${myUser.FullName} as Administrator`,
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: true,
      },
      {
        MessagesId: 5,
        IdOfUser: User3.PhoneNumber,
        FromUser: User3.FullName,
        Image: User3.Img,
        DateTimeOfMsg: new Date(`Wed Jul 05 2023 11:35:00`),
        message: "Hello4",
        IfRead: false,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: "873427cc-b0f0-4137-8a1e-8fe3992cc69e",
        IdOfUser: myUser.Id,
        FromUser: myUser.Name,
        Image: myUser.Img,
        DateTimeOfMsg: new Date(`Wed Jul 05 2023 12:11:00`),
        message: "aaaa",
        IfRead: false,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
    ],
  },
  "97d5f888-9bec-4524-a743-46b02f54fc98": {
    GroupName: "Group2",
    ImgGroup: profile,
    DateTime: new Date(`Sun Jul 02 2023 06:20:00`),
    Description: "description of the group",
    PrincipalAdminId: User2.PhoneNumber,
    PrincipalAdminName: User2.FullName,
    Friends: [
      {
        PhoneNumber: User2.PhoneNumber,
        FirstName: User2.FirstName,
        LastName: User2.LastName,
        Img: User2.Img,
        IfManager: true,
        Status: "Principal Admin",
        IfLeft: false,
        DepartureDate: [
          {
            DateOut: null,
          },
        ],
        JoiningDate: [
          {
            DateIn: new Date(`Sun Jul 02 2023 06:20:00`),
          },
        ],
      },
      {
        PhoneNumber: User1.PhoneNumber,
        FirstName: User1.FirstName,
        LastName: User1.LastName,
        Img: User1.Img,
        IfManager: true,
        Status: "Administrator",
        IfLeft: false,
        DepartureDate: [
          {
            DateOut: null,
          },
        ],
        JoiningDate: [
          {
            DateIn: new Date(`Sun Jul 02 2023 06:20:00`),
          },
        ],
      },
      {
        PhoneNumber: User3.PhoneNumber,
        FirstName: User3.FirstName,
        LastName: User3.LastName,
        Img: User3.Img,
        IfManager: false,
        Status: "",
        IfLeft: false,
        DepartureDate: [
          {
            DateOut: null,
          },
        ],
        JoiningDate: [
          {
            DateIn: new Date(`Sun Jul 02 2023 06:20:00`),
          },
        ],
      },
      {
        PhoneNumber: User4.PhoneNumber,
        FirstName: User4.FirstName,
        LastName: User4.LastName,
        Img: User4.Img,
        IfManager: false,
        Status: "",
        IfLeft: false,
        DepartureDate: [
          {
            DateOut: null,
          },
        ],
        JoiningDate: [
          {
            DateIn: new Date(`Sun Jul 02 2023 06:20:00`),
          },
        ],
      },
      {
        PhoneNumber: myUser.Id,
        FirstName: myUser.Name,
        LastName: myUser.Last,
        Img: myUser.Img,
        IfManager: false,
        Status: "",
        IfLeft: false,
        DepartureDate: [
          {
            DateOut: null,
          },
        ],
        JoiningDate: [
          {
            DateIn: new Date(`Sun Jul 02 2023 06:20:00`),
          },
        ],
      },
    ],
    messages: [
      {
        MessagesId: "608235eb-877b-42c2-92fe-131964c761d9",
        IdOfUser: "",
        FromUser: "",
        Image: "",
        DateTimeOfMsg: new Date(`Mon Jul 03 2023 08:16:00`),
        message: `${User2.FullName} created the group`,
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: true,
      },
      {
        MessagesId: "5b78335b-2e6b-400d-a296-970d77276772",
        IdOfUser: "",
        FromUser: "",
        Image: "",
        DateTimeOfMsg: new Date(`Mon Jul 03 2023 08:16:00`),
        message: `${User2.FullName} added ${User1.FullName}, ${User3.FullName}, ${User4.FullName}, ${myUser.FullName}`,
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: true,
      },
      {
        MessagesId: 1,
        IdOfUser: User2.PhoneNumber,
        FromUser: User2.FullName,
        Image: User2.Img,
        DateTimeOfMsg: new Date(`Mon Jul 03 2023 10:00:00`),
        message: "Hello!",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 2,
        IdOfUser: User1.PhoneNumber,
        FromUser: User1.FullName,
        Image: User1.Img,
        DateTimeOfMsg: new Date(`Tue Jul 04 2023 11:30:00`),
        message: "Hello1",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 3,
        IdOfUser: User1.PhoneNumber,
        FromUser: User1.FullName,
        Image: User1.Img,
        DateTimeOfMsg: new Date(`Tue Jul 04 2023 11:31:00`),
        message: "Hello2",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 4,
        IdOfUser: User4.PhoneNumber,
        FromUser: User4.FullName,
        Image: User4.Img,
        DateTimeOfMsg: new Date(`Tue Jul 04 2023 11:32:00`),
        message: "Hello3",
        IfRead: false,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 5,
        IdOfUser: User3.PhoneNumber,
        FromUser: User3.FullName,
        Image: User3.Img,
        DateTimeOfMsg: new Date(`Tue Jul 04 2023 10:00:00`),
        message: "Hello4?????",
        IfRead: false,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
    ],
  },
};

// achiya created the group
