// import { useSelector } from "react-redux";
import myPIC from "../img/myPIC.jpg";
import profile from "../img/profile-picture.jpg";

// const reduxMyUser = useSelector((state) => state.MyUser);
// console.log(reduxMyUser.Id);
// console.log(reduxMyUser.Name);

export const chatJSON = {
  A4321: {
    PhoneNumber: "A4321",
    FirstName: "User",
    LastName: "Name1",
    FullName: "User Name1",
    Image: myPIC,
    messages: [
      {
        MessagesId: 1,
        IdOfUser: "308",
        FromUser: "achiya",
        Image: myPIC,
        DateTimeOfMsg: new Date("Mon Jul 03 2023 10:00:00"),
        message: "Hello!",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 2,
        IdOfUser: "A4321",
        FromUser: "User Name1",
        Image: profile,
        DateTimeOfMsg: new Date("Tue Jul 04 2023 11:30:00"),
        message: "⊘ This message has been deleted",
        IfRead: true,
        IfDelete: true,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 3,
        IdOfUser: "A4321",
        FromUser: "User Name1",
        Image: profile,
        DateTimeOfMsg: new Date("Tue Jul 04 2023 11:31:00"),
        message: "are?",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 4,
        IdOfUser: "A4321",
        FromUser: "User Name1",
        Image: profile,
        DateTimeOfMsg: new Date("Tue Jul 04 2023 11:32:00"),
        message: "you?",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 5,
        IdOfUser: "308",
        FromUser: "achiya",
        Image: myPIC,
        DateTimeOfMsg: new Date("Fri Jul 07 2023 10:00:00"),
        message: "good!",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 6,
        IdOfUser: "A4321",
        FromUser: "User Name1",
        Image: profile,
        DateTimeOfMsg: new Date("Sat Jul 08 2023 11:30:00"),
        message: "How?",
        IfRead: false,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 7,
        IdOfUser: "A4321",
        FromUser: "User Name1",
        Image: profile,
        DateTimeOfMsg: new Date("Sun Jul 09 2023 11:31:00"),
        message: "are?",
        IfRead: false,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 8,
        IdOfUser: "A4321",
        FromUser: "User Name1",
        Image: profile,
        DateTimeOfMsg: new Date("Mon Jul 10 2023 11:32:00"),
        message: "you??????????????",
        IfRead: false,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
    ],
  },
  B8765: {
    PhoneNumber: "B8765",
    FirstName: "User",
    LastName: "Name2",
    FullName: "User Name2",
    Image: profile,
    messages: [
      {
        MessagesId: 1,
        IdOfUser: "308",
        FromUser: "achiya",
        Image: profile,
        DateTimeOfMsg: new Date("Mon Jul 03 2023 14:00:00"),
        message: "Hi there!",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 2,
        IdOfUser: "308",
        FromUser: "achiya",
        Image: profile,
        DateTimeOfMsg: new Date("Tue Jul 04 2023 15:30:00"),
        message: "I'm doing great!",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 3,
        IdOfUser: "B8765",
        FromUser: "User Name2",
        Image: profile,
        DateTimeOfMsg: new Date("Thu Jul 06 2023 16:30:00"),
        message: "How are you?",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 4,
        IdOfUser: "B8765",
        FromUser: "User Name2",
        Image: profile,
        DateTimeOfMsg: new Date("Thu Jul 06 2023 17:38:00"),
        message: "????",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 5,
        IdOfUser: "308",
        FromUser: "achiya",
        Image: profile,
        DateTimeOfMsg: new Date("Sun Jul 09 2023 14:00:00"),
        message: "Good",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 6,
        IdOfUser: "308",
        FromUser: "achiya",
        Image: profile,
        DateTimeOfMsg: new Date("Sun Jul 09 2023 15:30:00"),
        message: "and you?",
        IfRead: true,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 7,
        IdOfUser: "B8765",
        FromUser: "User Name2",
        Image: profile,
        DateTimeOfMsg: new Date("Sun Jul 09 2023 16:30:00"),
        message: "me?",
        IfRead: false,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
      {
        MessagesId: 8,
        IdOfUser: "B8765",
        FromUser: "User Name2",
        Image: profile,
        DateTimeOfMsg: new Date("Sun Jul 09 2023 17:38:00"),
        message: "????",
        IfRead: false,
        IfDelete: false,
        IfRemoved: false,
        IfFavorite: false,
        IfEdit: false,
        IfMessageGroup: false,
      },
    ],
  },
};

// messages: [
//   {
//     MessagesId: 1,
//     IdOfUser: "308",
//     FromUser: "achiya",
//     Image: myPIC,
//     DateTimeOfMsg: new Date("Mon Jul 03 2023 10:00:00"),
//     message: "⊘ This message has been deleted",
//     IfRead: true,
//     IfDelete: true,
//     IfRemoved: false,
//     IfFavorite: false,
//     IfEdit: false,
//     IfMessageGroup: false,
//   },
//   {
//     MessagesId: 2,
//     IdOfUser: "A4321",
//     FromUser: "User Name1",
//     Image: profile,
//     DateTimeOfMsg: new Date("Tue Jul 04 2023 11:30:00"),
//     message: "⊘ This message has been deleted",
//     IfRead: true,
//     IfDelete: true,
//     IfRemoved: false,
//     IfFavorite: false,
//     IfEdit: false,
//     IfMessageGroup: false,
//   },
//   {
//     MessagesId: 3,
//     IdOfUser: "A4321",
//     FromUser: "User Name1",
//     Image: profile,
//     DateTimeOfMsg: new Date("Tue Jul 04 2023 11:31:00"),
//     message: "⊘ This message has been deleted",
//     IfRead: true,
//     IfDelete: true,
//     IfRemoved: false,
//     IfFavorite: false,
//     IfEdit: false,
//     IfMessageGroup: false,
//   },
//   {
//     MessagesId: 4,
//     IdOfUser: "A4321",
//     FromUser: "User Name1",
//     Image: profile,
//     DateTimeOfMsg: new Date("Tue Jul 04 2023 11:32:00"),
//     message: "you?",
//     IfRead: true,
//     IfDelete: false,
//     IfRemoved: false,
//     IfFavorite: false,
//     IfEdit: false,
//     IfMessageGroup: false,
//   },
//   {
//     MessagesId: 5,
//     IdOfUser: "308",
//     FromUser: "achiya",
//     Image: myPIC,
//     DateTimeOfMsg: new Date("Fri Jul 07 2023 10:00:00"),
//     message: "good!",
//     IfRead: true,
//     IfDelete: false,
//     IfRemoved: false,
//     IfFavorite: false,
//     IfEdit: false,
//     IfMessageGroup: false,
//   },
//   {
//     MessagesId: 6,
//     IdOfUser: "A4321",
//     FromUser: "User Name1",
//     Image: profile,
//     DateTimeOfMsg: new Date("Sat Jul 08 2023 11:30:00"),
//     message: "How?",
//     IfRead: false,
//     IfDelete: false,
//     IfRemoved: false,
//     IfFavorite: false,
//     IfEdit: false,
//     IfMessageGroup: false,
//   },
//   {
//     MessagesId: 7,
//     IdOfUser: "A4321",
//     FromUser: "User Name1",
//     Image: profile,
//     DateTimeOfMsg: new Date("Sun Jul 09 2023 11:31:00"),
//     message: "are?",
//     IfRead: false,
//     IfDelete: false,
//     IfRemoved: false,
//     IfFavorite: false,
//     IfEdit: false,
//     IfMessageGroup: false,
//   },
//   {
//     MessagesId: 8,
//     IdOfUser: "A4321",
//     FromUser: "User Name1",
//     Image: profile,
//     DateTimeOfMsg: new Date("Mon Jul 10 2023 11:32:00"),
//     message: "you??????????????",
//     IfRead: false,
//     IfDelete: false,
//     IfRemoved: false,
//     IfFavorite: false,
//     IfEdit: false,
//     IfMessageGroup: false,
//   },
// ],
